### ISSUE TITLE
Keep image pixelated

### ISSUE THREAD

**Issue by MarcSkovMadsen** [manzt/ipymario#1]
If you want to keep the button pixelated when you increase the size, you can do that by updating the css to:

```css
.ipymario > canvas {
    animation-fill-mode: both;
    image-rendering: pixelated; /* Ensures the image stays pixelated */
    image-rendering: crisp-edges; /* For additional support in some browsers */
}
```
